services:
  web:
    image: nginx:stable-alpine-otel
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - backend
    extra_hosts:
      - signoz:host-gateway
  backend:
    container_name: backend-container
    build:
      context: ./docker/backend/python
    environment:
      OTEL_PYTHON_LOG_CORRELATION: true
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_PYTHON_LOG_FORMAT: "%(msg)s [span_id=%(span_id)s]"
      OTEL_PYTHON_LOG_LEVEL: debug
      OTEL_RESOURCE_ATTRIBUTES: service.name=backend_service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      DB_USER: docker
      DB_PASSWORD: docker
      DB_HOST: db
      DATABASE: japanpost
      TZ: Asia/Tokyo
    volumes:
      - ./docker/backend/python/app:/app
    ports:
      - 5002
    depends_on:
      - db
    extra_hosts:
      - signoz:host-gateway
  db:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: japanpost
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-docker}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306

  otelcol-gateway:
    image: otel/opentelemetry-collector-contrib
    container_name: otelcol-gateway-container
    command: [ "--config=/etc/otelcol-config.yml" ]
    environment:
      MYSQL_OTELCOL_USER: ${MYSQL_OTELCOL_USER:-root}
      MYSQL_OTELCOL_PASSWORD: ${MYSQL_OTELCOL_PASSWORD:-root}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/otel-collector/config.yml:/etc/otelcol-config.yml
    extra_hosts:
      - signoz:host-gateway

