services:
  nginx:
    image: nginx:stable-alpine-otel
    ports:
      - 80:80
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/conf.d:/etc/nginx/conf.d
    extra_hosts:
      - signoz:host-gateway
  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: japanpost
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306

  otelcol:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otelcol-config.yml" ]
    environment:
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/otel-collector/config.yml:/etc/otelcol-config.yml
    extra_hosts:
      - signoz:host-gateway

