services:

  nginx:
    container_name: nginx
    image: nginx:1.27-otel
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - app

  grafana:
    container_name: grafana
    image: grafana/grafana:11.1.0
    volumes:
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=pyroscope-panel, grafana-clock-panel, grafana-simple-json-datasource
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary traceToProfiles tracesEmbeddedFlameGraph
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - tempo
      - loki
      - pyroscope
      - opentelemetry-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.53.0
    command:
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--enable-feature=otlp-write-receiver"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  tempo:
    container_name: tempo
    image: grafana/tempo:2.5.0
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - 3200:3200 # http
      - 9096:9096 # grpc
      - 4417:4417 # otlp grpc
      - 4418:4418 # otlp http
      - 14268:14268 # jaeger

  loki:
    container_name: loki
    image: grafana/loki:3.1.0
    command:
      - "-config.file=/etc/loki/loki.yaml"
      - "-print-config-stderr"  # for debug
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml
    ports:
      - 3100:3100 # http
      - 9095:9095 # grpc

  opentelemetry-collector:
    container_name: opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:0.104.0
    command:
      - "--config=/etc/otel-config.yaml"
    volumes:
      - ./opentelemetry-collector/otel-config.yaml:/etc/otel-config.yaml
      - ./nginx/log:/var/log/nginx
    ports:
      - 4317:4317   # grpc
      - 4318:4318   # http
    depends_on:
      - prometheus
      - tempo
      - loki

  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:1.6.1
    command: [ "-config.file=/etc/pyroscope.yaml" ]
    environment:
      JAEGER_AGENT_HOST: tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    volumes:
      - ./pyroscope/pyroscope.yaml:/etc/pyroscope.yaml
    ports:
    - 4040:4040

  app:
    container_name: sample-app
    image: sample-app
    build:
      context: ./app
    environment:
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_LOGS_EXPORTER: otlp
      OTEL_PYTHON_LOG_CORRELATION: true
      OTEL_PYTHON_LOG_LEVEL: debug
      OTEL_RESOURCE_ATTRIBUTES: service.name=sample-app
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
    ports:
      - 5002:5002
    depends_on:
      - opentelemetry-collector

  mimir:
    image: grafana/mimir:2.13.0
    container_name: mimir
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - ./mimir/data:/data/mimir
    ports:
      - 9009:9009
