services:
  opentelemetry-collector:
    container_name: opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - "--config=/etc/opentelemetry-collector.yaml"
    volumes:
      - ./opentelemetry-collector.yaml:/etc/opentelemetry-collector.yaml
    ports:
      - "4317:4317"   # grpc
      - "4318:4318"   # http
