services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=pyroscope-panel, grafana-clock-panel, grafana-simple-json-datasource
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary traceToProfiles tracesEmbeddedFlameGraph
    volumes:
      - "./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./dashboardproviders.yaml:/etc/grafana/provisioning/dashboards/dashboardproviders.yaml"
      - "./dashboards/opentelemetry:/var/lib/grafana/dashboards/opentelemetry"
    ports:
      - "3000:3000"
