otel_service_name nginx_serivce;
otel_trace_context propagate;
otel_exporter {
  endpoint signoz:4317;
}

server {
  listen 80 default_server;
  server_name _;

  location /status {
    stub_status on;
    access_log  off;
  }

  location / {
    otel_trace on;
    otel_span_name $request_uri;

    proxy_pass http://backend:5002;
  }
}
