receivers:
  nginx:
    endpoint: "http://web:80/status"

  mysql:
    endpoint: db:3306
    username: ${env:MYSQL_OTELCOL_USER}
    password: ${env:MYSQL_OTELCOL_PASSWORD}
    database: japanpost
    collection_interval: 10s
    initial_delay: 1s
    tls:
      insecure: true
    statement_events:
      digest_text_limit: 120
      time_limit: 24h
      limit: 250

exporters:
  otlp:
    endpoint: http://signoz:4317
    tls:
      insecure: true

processors:
  resourcedetection:
    detectors: [env, system]
  batch:

service:
  pipelines:
    metrics/mysql:
      receivers: [mysql]
      processors: [resourcedetection]
      exporters: [otlp]
    metrics/nginx:
      receivers: [nginx]
      processors: [batch]
      exporters: [otlp]
